import { ArrowUpRight, Check, ChevronDown, Menu, MessageCircle, Phone, Sparkles, Star, X } from 'lucide-react'
import { FaFacebookF, FaInstagram } from 'react-icons/fa6'
import { useState } from 'react'
import './App.css'

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const whatsappUrl = 'https://wa.me/61407109257?text=Hi%20ABC%20Floor%20Sanding%2C%20I%27d%20like%20a%20free%20quote.'
  const googleReviewsUrl = 'https://www.google.com/search?q=google+review+abc+floor+sanding&oq=google+review+abc+floor+sanding&sourceid=chrome&ie=UTF-8'

  return (
    <div className="site-shell">
      <div className="announcement"><span>Brisbane's timber floor specialists</span><a href={whatsappUrl}>Message us on WhatsApp <ArrowUpRight size={15} /></a></div>
      <header className="nav"><a className="brand" href="#top"><span className="brand-mark">ABC</span><span>FLOOR<br /><b>SANDING</b></span></a><nav className={menuOpen ? 'nav-links open' : 'nav-links'}><a href="#services" onClick={() => setMenuOpen(false)}>Services</a><a href="#process" onClick={() => setMenuOpen(false)}>Our process</a><a href="#about" onClick={() => setMenuOpen(false)}>About us</a><a href="#contact" onClick={() => setMenuOpen(false)}>Contact</a></nav><div className="nav-actions"><a className="phone-link" href="tel:+61407109257"><Phone size={17} />0407 109 257</a><a className="button button-dark nav-quote" href="#contact">Get a free quote <ArrowUpRight size={17} /></a><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <X /> : <Menu />}</button></div></header>

      <main id="top">
        <section className="hero"><div className="hero-copy"><p className="eyebrow"><span className="eyebrow-line" /> FLOOR SANDING BRISBANE</p><h1>Old floors.<br /><em>New life.</em></h1><p className="hero-text">Beautiful timber floors, finished properly. We sand, restore and protect floors across Brisbane with care that shows in every detail.</p><div className="hero-buttons"><a className="button button-orange" href="#contact">Get your free quote <ArrowUpRight size={18} /></a><a className="text-link" href={whatsappUrl}><MessageCircle size={19} /> Chat on WhatsApp</a></div><a className="hero-note" href={googleReviewsUrl} target="_blank" rel="noreferrer"><div className="avatar-stack"><span>G</span><span>G</span><span>G</span></div><span><b>Read our Google reviews</b><br />See what Brisbane homeowners say</span><ArrowUpRight size={15} /></a></div><div className="hero-image"><img src="https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=85" alt="Warmly finished timber floor in a bright home" /><div className="image-label"><Sparkles size={16} /><span>Made to be lived on</span></div></div></section>

        <section className="trust-bar"><span className="trust-intro">THE ABC DIFFERENCE</span><div><strong>20+</strong><span>years of experience</span></div><div><strong>Google</strong><span>customer reviews</span></div><div><strong>100%</strong><span>dust-controlled</span></div><div className="trust-end"><span>Quality work.<br /><b>Fair prices.</b></span><ArrowUpRight /></div></section>

        <section className="section services-section" id="services"><div className="section-heading"><div><p className="eyebrow"><span className="eyebrow-line" /> WHAT WE DO</p><h2>We make good floors<br /><em>great again.</em></h2></div><p>From a tired family room to a complete commercial fit-out, our team brings old timber back to its best.</p></div><div className="services-grid"><ServiceCard number="01" title="Timber floor sanding" text="A smooth, clean foundation that brings out the natural character of your timber." image="https://images.unsplash.com/photo-1615529162924-f8605388461d?auto=format&fit=crop&w=700&q=80" /><ServiceCard number="02" title="Polishing & finishing" text="Durable, beautiful finishes using the industry's most trusted products." image="https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=700&q=80" /><ServiceCard number="03" title="Decks & verandahs" text="Weathered outdoor timber, refreshed for long afternoons and easy living." image="https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=700&q=80" /></div><a className="all-services" href="#contact">View all services <ArrowUpRight size={17} /></a></section>

        <section className="split-section" id="about"><div className="split-image"><img src="https://images.unsplash.com/photo-1549497538-303791108f95?auto=format&fit=crop&w=1000&q=85" alt="Craftsperson working on timber flooring" /><span className="vertical-note">CRAFTED IN BRISBANE · 2004</span></div><div className="split-copy"><p className="eyebrow"><span className="eyebrow-line" /> WHY ABC</p><h2>Good work is<br /><em>in the details.</em></h2><p>Our floor sanders are experienced, efficient and genuinely proud of the finish they leave behind. We use professional machinery, careful preparation and quality products on every job.</p><ul className="check-list"><li><Check size={17} /> Honest, competitive pricing</li><li><Check size={17} /> Careful, tidy workmanship</li><li><Check size={17} /> Free quotes with no pressure</li></ul></div></section>

        <section className="process-section" id="process"><div className="process-top"><div><p className="eyebrow"><span className="eyebrow-line" /> SIMPLE FROM START TO FINISH</p><h2>Let’s get your floor<br /><em>back on its feet.</em></h2></div><p>No jargon, no surprises. Just a clear plan and a finish you’ll be proud to show off.</p></div><div className="process-grid"><Process number="01" title="Tell us about your floor" text="Send a few details or photos. We’ll get back to you quickly." /><Process number="02" title="Get a clear quote" text="We’ll inspect the space and explain exactly what’s involved." /><Process number="03" title="Love the finish" text="We take care of the hard work, then leave your space spotless." /></div></section>

        <section className="testimonial"><div className="quote-mark"><Star fill="currentColor" size={45} /></div><p className="eyebrow review-eyebrow">GOOGLE REVIEWS</p><blockquote>See the latest feedback from customers who trusted ABC with their floors.</blockquote><a className="button button-light" href={googleReviewsUrl} target="_blank" rel="noreferrer">Read our Google reviews <ArrowUpRight size={18} /></a></section>

        <section className="contact-section" id="contact"><div><p className="eyebrow"><span className="eyebrow-line" /> READY WHEN YOU ARE</p><h2>Let’s talk about<br /><em>your floors.</em></h2><p>Tell us what you’re working with and we’ll help you figure out the best next step.</p><a className="contact-whatsapp" href={whatsappUrl}><MessageCircle size={22} /> WhatsApp us on <b>0407 109 257</b></a></div><form onSubmit={(event) => event.preventDefault()}><label>Your name<input type="text" placeholder="Jane Smith" /></label><label>How can we help?<select defaultValue=""><option value="" disabled>Select a service</option><option>Timber floor sanding</option><option>Polishing & finishing</option><option>Decks & verandahs</option><option>Commercial flooring</option></select><ChevronDown className="select-icon" size={18} /></label><label>Tell us a little more<textarea placeholder="A few details about your floor..."></textarea></label><button className="button button-orange" type="submit">Request a free quote <ArrowUpRight size={18} /></button></form></section>
      </main>
      <footer><a className="brand" href="#top"><span className="brand-mark">ABC</span><span>FLOOR<br /><b>SANDING</b></span></a><span>Floor sanding Brisbane & surrounds</span><div className="social-links"><a href="https://www.facebook.com/abcfloor" target="_blank" rel="noreferrer" aria-label="ABC Floor Sanding on Facebook"><FaFacebookF aria-hidden="true" /></a><a href="https://www.instagram.com/abcfloorsanding" target="_blank" rel="noreferrer" aria-label="ABC Floor Sanding on Instagram"><FaInstagram aria-hidden="true" /></a></div><span>© 2024 ABC Floor Sanding</span></footer>
      <a className="whatsapp-float" href={whatsappUrl} aria-label="Message ABC Floor Sanding on WhatsApp"><MessageCircle size={25} /></a>
    </div>
  )
}

function ServiceCard({ number, title, text, image }) { return <article className="service-card"><div className="service-image"><img src={image} alt="" /><span>{number}</span></div><div className="service-card-copy"><h3>{title}</h3><p>{text}</p><a href="#contact" aria-label={`Get a quote for ${title}`}><ArrowUpRight size={19} /></a></div></article> }
function Process({ number, title, text }) { return <div className="process-item"><span className="process-number">{number}</span><h3>{title}</h3><p>{text}</p></div> }

export default App
